services:
  mini-project-spring:
    image: 'spring-mini-project-image:latest'
    build:
      context: .
    container_name: mini-project-spring
    depends_on:
      - mini-project-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mini-project-postgres:5432/product_order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1231
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"

  mini-project-postgres:
    image: postgres:16
    container_name: mini-project-postgres
    restart: always
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 1231
      POSTGRES_DB : mini_project_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
