services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/product_order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1231
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8081:8080"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 1231
      POSTGRES_DB : product_order_db
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
