spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "*"
            allow-credentials: false

      routes:
        - id: keycloak-admin-client-route
          uri: lb://KEYCLOAK-ADMIN-CLIENT
          predicates:
            - Path=/keycloak-admin-client/v3/api-docs, /api/v1/**

        - id: task-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/task-service/v3/api-docs, /api/v1/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /keycloak-admin-client/v3/api-docs
        name: Keycloak Admin Client
      - url: /task-service/v3/api-docs
        name: Task Service Client

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8888
