spring:
  application:
    name: task-config
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8088/"

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    show-sql: ${spring.jpa.show-sql}
    properties:
      hibernate:
        dialect: ${spring.jpa.properties.hibernate.dialect}

openapi:
  service:
    title: Task Service Client
    version: 3.3.2
    url: http://localhost:8888

springdoc:
  api-docs:
    path: /task-service/v3/api-docs
  swagger-ui:
    path: /task-service/swagger-ui.html


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#resilience4j:
#  circuitbreaker:
#    instances:
#      task-service-circuit-breaker:
#        register-health-indicator: true
#        event-consumer-buffer-size: 10
#        failure-rate-threshold: 50
#        minimum-number-of-calls: 5
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state: 5s
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 10
#        sliding-window-type: COUNT_BASED
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0

server:
  port: 8089