spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuoyivong/spring-cloud-config-server.git
          clone-on-start: true
          default-label: client-configuration

server:
  port: 8088
